---
- name: Install and configure SSHD
  hosts: all
  gather_facts: false

  tasks:
    - name: Install latest sshd
      ansible.builtin.package:
        name: openssh-server
        state: latest

    - name: Copy configuration file
      ansible.builtin.copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'
    
    - name: start the service
      ansible.builtin.service:
        name: sshd
        state: started 

    - name: Allow the traffic through firewall
      ansible.posix.firewalld:
        permanent: true
        service: ssh
        state: enabled
        immediate: true
    
